// rxjs-angular/src/app/fetching.component.ts
import {CommonModule} from '@angular/common';
import {Component} from '@angular/core';
import {
  getPostsCount,
  posts$,
  refinePostsData,
  refineUsersData,
  reloadPosts,
  reloadUsers,
  users$
} from '@buslowicz/shared';
import {BehaviorSubject} from 'rxjs';

@Component({
  selector: 'app-fetching',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    ul {
      list-style: none;
      padding: 0;
      max-height: 400px;
      overflow: auto;
    }

    .users {
      margin-right: 20px;
    }

    .users > li {
      cursor: pointer;
    }
    
    .posts {
      column-count: 2;
    }

    .lists {
      display: flex;
    }
  `],
  template: `
    <h1>Fetching</h1>
    <button (click)="reloadUsers()">Reload users</button>
    <button (click)="reloadPosts()">Reload posts</button>
    <input type="range" #maxPosts [value]="maxPosts$ | async" (input)="maxPosts$.next(maxPosts.valueAsNumber)" min="1" [max]="postsCount$ | async">
    <span>{{maxPosts$ | async}} / {{postsCount$ | async}}</span>
    <div class="lists">
      <ul class="users">
        <li>
          <button (click)="selectedUser$.next(null)">Reset user filter</button>
        </li>
        <li *ngFor="let user of users$ | async" (click)="selectedUser$.next(user.id)">{{user.name}}</li>
      </ul>
      <ul class="posts">
        <li *ngFor="let post of posts$ | async">{{post.title}} (by {{post.user.name}}))</li>
      </ul>
    </div>
  `,
})
export class FetchingComponent {
  maxPosts$ = new BehaviorSubject<number>(10);
  selectedUser$ = new BehaviorSubject<string | null>(null);

  users$ = users$.pipe(refineUsersData());
  posts$ = posts$.pipe(refinePostsData(this.selectedUser$, this.maxPosts$));
  postsCount$ = posts$.pipe(getPostsCount(this.selectedUser$));

  reloadUsers() {
    reloadUsers();
  }

  reloadPosts() {
    reloadPosts();
  }
}

// rxjs-react/src/app/fetching.component.tsx
import {
  getPostsCount, Post,
  posts$,
  refinePostsData,
  refineUsersData,
  reloadPosts,
  reloadUsers, User,
  users$
} from '@buslowicz/shared';
import {useEffect, useMemo, useState} from 'react';
import {BehaviorSubject, combineLatest} from 'rxjs';
import styled from 'styled-components';

const Wrapper = styled.div`
  ul {
    list-style: none;
    padding: 0;
    max-height: 400px;
    overflow: auto;
  }

  .users {
    margin-right: 20px;
  }

  .users > li {
    cursor: pointer;
  }

  .posts {
    column-count: 2;
  }

  .lists {
    display: flex;
  }
`;

export function FetchingComponent() {
  const [maxPosts, setMaxPosts] = useState(10);
  const [selectedUser, setSelectedUser] = useState<string | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [posts, setPosts] = useState<(Post & { user: User })[]>([]);
  const [postsCount, setPostsCount] = useState(0);
  const {maxPosts$, selectedUser$} = useMemo(() => {
    return {
      maxPosts$: new BehaviorSubject<number>(10),
      selectedUser$: new BehaviorSubject<string | null>(null),
    };
  }, []);

  useEffect(() => maxPosts$.next(maxPosts), [maxPosts]);
  useEffect(() => selectedUser$.next(selectedUser), [selectedUser]);

  useEffect(() => {
    const subscription = combineLatest([
      users$.pipe(refineUsersData()),
      posts$.pipe(refinePostsData(selectedUser$, maxPosts$)),
      posts$.pipe(getPostsCount(selectedUser$)),
    ]).subscribe(([users, posts, postsCount]) => {
      setUsers(users);
      setPosts(posts);
      setPostsCount(postsCount);
    });
    return () => subscription.unsubscribe();
  }, [maxPosts$, selectedUser$]);

  return (
    <Wrapper>
      <h1>Fetching</h1>
      <button onClick={reloadUsers}>Reload users</button>
      <button onClick={reloadPosts}>Reload posts</button>
      <input type="range" value={maxPosts} min="1" max={postsCount} onInput={({target}) => setMaxPosts((target as HTMLInputElement).valueAsNumber)}/>
      <span>{maxPosts} / {postsCount}</span>
      <div className="lists">
        <ul className="users">
          <li>
            <button onClick={() => setSelectedUser(null)}>Reset user filter</button>
          </li>
          {users.map(user => (<li key={user.id} onClick={() => setSelectedUser(user.id)}>{user.name}</li>))}
        </ul>
        <ul className="posts">
          {posts.map(post => (<li key={post.id}>{post.title} (by {post.user.name})</li>))}
        </ul>
      </div>
    </Wrapper>
  );
}
